spring:
  datasource:
    url: jdbc:mysql://172.17.0.2/agro?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
    username: root
    password: P@ssword1;
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

keycloak:
  admin_url: https://d1isjhghszo6bn.cloudfront.net/auth/admin/realms/
  url: https://d1isjhghszo6bn.cloudfront.net/auth/
  client_secret: 517e3d1d-220a-4c6c-8a36-8c96535e56a2
  admin_password: password
  admin_username: admin
  smtp_host: alt3.gmail-smtp-in.l.google.com
  realm_name: feng-test
  grant_type: password
  client_id: dev-test
  
sfactr:
  app_id: 3-0029-6271-7845-607
  secret_key: QKGqZbs2dAxygaNp
  hash_key: PFm679kpXjb4
  base_url: https://api2.sfactr.uk/
  